/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SMonacoEditor {
    }
}
declare global {
    interface HTMLSMonacoEditorElement extends Components.SMonacoEditor, HTMLStencilElement {
    }
    var HTMLSMonacoEditorElement: {
        prototype: HTMLSMonacoEditorElement;
        new (): HTMLSMonacoEditorElement;
    };
    interface HTMLElementTagNameMap {
        "s-monaco-editor": HTMLSMonacoEditorElement;
    }
}
declare namespace LocalJSX {
    interface SMonacoEditor {
    }
    interface IntrinsicElements {
        "s-monaco-editor": SMonacoEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "s-monaco-editor": LocalJSX.SMonacoEditor & JSXBase.HTMLAttributes<HTMLSMonacoEditorElement>;
        }
    }
}
